### ISSUE TITLE
OpenIdConnectError when client credential grant type

### ISSUE THREAD

**Issue by kaito3desuyo** [panva/node-openid-client#106]
Hello.

I'm trying to authorize client credential grant type using node-openid-provider and node-openid-client.
However, the following error occurs.

```
{ OpenIdConnectError: unauthorized_client (requested grant type is restricted to this client)
    at Client.requestErrorHandler (/home/myName/Dropbox/Program/myProject/node_modules/openid-client/lib/helpers/error_handler.js:16:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  error: 'unauthorized_client',
  error_description: 'requested grant type is restricted to this client' }
```

Each code is as follows.

Provider index.js
```
const Provider = require('oidc-provider')
const issuer = 'http://localhost:3030'
const config = {
    features: { 
        clientCredentials: true,
        introspection: true,
        revocation: true,
        devInteractions: true
    } 
}

const clients = [
    {
        client_id: "0",
        client_secret: "0",
        grant_type: ["client_credentials"],
        redirect_uris: [
            'http://localhost:3000/auth/cb'
        ]
    }
]

const oidc = new Provider(issuer, config)
oidc.initialize({ clients }).then(() => {
    console.log(oidc.callback)
    console.log(oidc.app)
    oidc.app.listen(3030)
})
```

Client on express app.js
```
module.exports = issuer => {
    const express = require("express")
    const { Nuxt, Builder } = require("nuxt")
    const session = require("express-session")
    const passport = require("passport")
    const Strategy = require("openid-client").Strategy

    /*
     * Open ID Connect Implement
     */
    const client = new issuer.Client({
        client_id: "0",
        client_secret: "0"
    })

    client
        .grant({
            grant_type: "client_credentials"
        })
        .then(done => {
            console.log(done)
        })
        .catch(err => {
            console.log(err)
        })

    const params = {
        redirect_uri: "http://localhost:3000/auth/cb"
    }

    passport.use(
        "oidc",
        new Strategy({ client, params }, (tokenset, userinfo, done) => {
            console.log("tokenset", tokenset)
            console.log("access_token", tokenset.access_token)
            console.log("id_token", tokenset.id_token)
            console.log("claims", tokenset.claims)
            console.log("userinfo", userinfo)

            if (tokenset.claims.sub !== "0") {
                return done(null)
            }
            return done(null, tokenset.claims.sub)
        })
    )
    passport.serializeUser(function(user, done) {
        done(null, user)
    })

    passport.deserializeUser(function(id, done) {
        done(null, { client_id: id })
    })

    const app = express()

    let config = require("./nuxt.config.js")
    config.dev = !(process.env.NODE_ENV === "production")
    const nuxt = new Nuxt(config)

    if (config.dev) {
        const builder = new Builder(nuxt)
        builder.build()
    }

    app.use(
        session({
            secret: "hogefuga",
            resave: false,
            saveUninitialized: false
        })
    )
    app.use(passport.initialize())
    app.use(passport.session())

    app.get("/auth", passport.authenticate("oidc"))
    app.get(
        "/auth/cb",
        passport.authenticate("oidc", {
            successRedirect: "/",
            failureRedirect: "/users"
        })
    )

    const api = require("./api")

    app.use("/api", api)
    app.use(nuxt.render)

    return app
}
```
Is there a solution?

Thank you.

**Comment by panva** [comment]
```js
const clients = [
    {
        client_id: "...",
        client_secret: "...",
        grant_types: ["client_credentials"],
        redirect_uris: [],
        response_types: [],
    }
]
```

**Comment by kaito3desuyo** [comment]
It works.
It was a very simple typing mistake.

Thank you.
