### ISSUE TITLE
help needed: using open-id-client with passport

### ISSUE THREAD

**Issue by eman-moh** [panva/node-openid-client#12]
When I run my express app, I get this error:
`
TypeError: Cannot read property 'callbackParams' of undefined
   at OpenIDConnectStrategy.authenticate (../grant/node_modules/openid-client/lib/passport_strategy.js:63:31)
   at attempt (../grant/node_modules/passport/lib/middleware/authenticate.js:348:16)
`
I'm including code snippet from my app.js file:

```
exports.appPromise = new Promise(resolve => {
  Issuer.discover('xxxxxxx')
    .then(function (identityIssuer) {
      app.use(bodyParser.json());
      app.use(bodyParser.urlencoded({
        extended: false
      }));
      app.use(cookieParser());
      app.use(express.static(path.join(__dirname, 'public')));
      app.use(cookieSession({
        secret: 'xxxx',
        resave: false,
        saveUninitialized: true,
        cookie: {
          secure: true
        }
      }));
      let client = new identityIssuer.Client({
        client_id: 'emailAPI',
        client_secret: 'xx'
      });
      passport.use('oidc', new Strategy(client, (tokenset, userinfo, done) => {
        console.log('tokenset', tokenset);
        console.log('access_token', tokenset.access_token);
        console.log('id_token', tokenset.id_token);
        console.log('claims', tokenset.claims);
        console.log('userinfo', userinfo);
        return done(null, false);
      }));
      app.use(passport.initialize());
      app.use('/users', passport.authenticate('oidc'), function (req, res) {
        console.log('httpOptions %j', Issuer.defaultHttpOptions);
        res.send(client.authorizationUrl({
          redirect_uri: 'xxx',
          scope: 'openid email'
        }));
      });
      resolve(app);
    });
});
```

**Comment by panva** [comment]
can you post your package.json and/or yarn.lock?

**Comment by panva** [comment]
Just for reference, my server file.
```js
'use strict';

const Issuer = require('.').Issuer;
const Strategy = require('.').Strategy;

const app = require('express')();
const passport = require('passport');
const bodyParser = require('body-parser');
const cookieParser = require('cookie-parser');
const cookieSession = require('cookie-session');

Issuer.discover('https://guarded-cliffs-8635.herokuapp.com').then(function (issuer) {
  return issuer.Client.register({
    redirect_uris: ['http://lvh.me:3000/users'],
  });
}).then(function (client) {
  client.CLOCK_TOLERANCE = 5;
  app.use(bodyParser.urlencoded());
  app.use(cookieParser());
  app.use(cookieSession({ secret: 'foo', resave: false, saveUnitialized: true, cookie: { secure: false } }));

  passport.use('oidc', new Strategy(client, (tokenset, done) => {
    console.log(tokenset);
    return done(null, false);
  }));

  app.use(passport.initialize());
  app.use('/users', passport.authenticate('oidc'), function (req, res) {
    res.send('foo');
  });

  app.listen(3000);
});
```

**Comment by panva** [comment]
@floydprice too many moving pieces to tell what's wrong, are you getting a state back on your response? can you see it in the authorization response?
