### ISSUE TITLE
openid-client package throws `invalid IncomingMessage method` error while callback request

### ISSUE THREAD

**Issue by ktikku** [panva/node-openid-client#229]
**Describe the bug**

While executing OpenID Connect flow using Azure AD, when we hit /oauth2/v2.0/authorize, after the user enters his credentials, Azure AD sends back a code via callback url.
According to openid-client package, this callback request must be either a GET or a POST request. We're assuming that the callback request can be a non GET or POST request, that can be one of the sources for the error.
The error originates from client.js file.

We don't get the error while callback request consistently, it happens once every 50 times.

Attaching error logs for reference: 
```
Feb 05 16:49:05 cirr-lillydev-prod app/web.1 TypeError: invalid IncomingMessage method
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at Client.callbackParams (/app/node_modules/openid-client/lib/client.js:359:17)
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at /app/node_modules/openid-client/lib/passport_strategy.js:84:30
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at OpenIDConnectStrategy.authenticate (/app/node_modules/openid-client/lib/passport_strategy.js:174:5)
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at attempt (/app/node_modules/passport/lib/middleware/authenticate.js:366:16)
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at authenticate (/app/node_modules/passport/lib/middleware/authenticate.js:367:7)
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at /app/node_modules/cirrus-oidc-auth-module/dist/auth.js:282:15
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at WebFrameworkShim.applySegment (/app/node_modules/newrelic/lib/shim/shim.js:1424:20)
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at _applyRecorderSegment (/app/node_modules/newrelic/lib/shim/shim.js:1015:20)
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at _doRecord (/app/node_modules/newrelic/lib/shim/shim.js:994:17)
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at /app/node_modules/newrelic/lib/shim/shim.js:965:24
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at /app/node_modules/express/lib/router/index.js:284:7
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at next (/app/node_modules/express/lib/router/index.js:275:10)
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at boundNext (/app/node_modules/newrelic/lib/shim/webframework-shim.js:1053:30)
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at WebFrameworkShim.applySegment (/app/node_modules/newrelic/lib/shim/shim.js:1424:20)
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at wrapper (/app/node_modules/newrelic/lib/shim/shim.js:2065:17)
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at SessionStrategy.strategy.pass (/app/node_modules/passport/lib/middleware/authenticate.js:343:9)
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at SessionStrategy.authenticate (/app/node_modules/passport/lib/strategies/session.js:75:10)
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at attempt (/app/node_modules/passport/lib/middleware/authenticate.js:366:16)
Feb 05 16:49:05 cirr-lillydev-prod app/web.1     at authenticate (/app/node_modules/passport/lib/middleware/authenticate.js:367:7)
```
**To Reproduce**
Issuer and Client configuration: (inline or gist) - Don't forget to redact your secrets.
```js
// Issuer configuration (issuer.metadata) and how it is constructed (discovery or manual?)
It is constructed by discovery
{
 "token_endpoint": "https://login.microsoftonline.com/18a59a81-eea8-4c30-948a-d8824cdc2580/oauth2/v2.0/token",
"token_endpoint_auth_methods_supported": [
"client_secret_post",
"private_key_jwt",
"client_secret_basic"
],
"jwks_uri": "https://login.microsoftonline.com/18a59a81-eea8-4c30-948a-d8824cdc2580/discovery/v2.0/keys",
"response_modes_supported": [
"query",
"fragment",
"form_post"
],
"subject_types_supported": [
"pairwise"
],
"id_token_signing_alg_values_supported": [
"RS256"
],
"response_types_supported": [
"code",
"id_token",
"code id_token",
"id_token token"
],
"scopes_supported": [
"openid",
"profile",
"email",
"offline_access"
],
"issuer": "https://login.microsoftonline.com/18a59a81-eea8-4c30-948a-d8824cdc2580/v2.0",
"request_uri_parameter_supported": false,
"userinfo_endpoint": "https://graph.microsoft.com/oidc/userinfo",
"authorization_endpoint": "https://login.microsoftonline.com/18a59a81-eea8-4c30-948a-d8824cdc2580/oauth2/v2.0/authorize",
"http_logout_supported": true,
"frontchannel_logout_supported": true,
"end_session_endpoint": "https://login.microsoftonline.com/18a59a81-eea8-4c30-948a-d8824cdc2580/oauth2/v2.0/logout",
"claims_supported": [
"sub",
"iss",
"cloud_instance_name",
"cloud_instance_host_name",
"cloud_graph_host_name",
"msgraph_host",
"aud",
"exp",
"iat",
"auth_time",
"acr",
"nonce",
"preferred_username",
"name",
"tid",
"ver",
"at_hash",
"c_hash",
"email"
],
"tenant_region_scope": "NA",
"cloud_instance_name": "microsoftonline.com",
"cloud_graph_host_name": "graph.windows.net",
"msgraph_host": "graph.microsoft.com",
"rbac_url": "https://pas.windows.net"
}

Steps to reproduce the behaviour:
1. openid-client package makes a call to Azure AD with client-id, redirect-url, client-secret, scope, response_type and response_mode.
2.  invoke Open ID Connect flow - User enters his credentials
3.  The auth server sends back a callback request with the code 
4. The Client.js file throws TypeError: invalid IncomingMessage method error.

**Expected behaviour**
We expected the code to be fetched from the query parameter and the module to make a call to the token end point to get the access-token.

**Environment:**
 - openid-client version: v3.9.1
 - node version: v12.14.1

**Additional context**
Add any other context about the problem here.

 - [ ] the bug is happening on latest openid-client too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
The exhibited openid-client behaviour is correct, there's no bug or issue. If you're getting requests other than GET (for default response_mode) or POST (for response_mode=form_post) then investigate why you're getting those requests in the first place.

This throw is a safe guard, letting you know you might be too permissive in your routing.

**Comment by ktikku** [comment]
> The exhibited openid-client behaviour is correct, there's no bug or issue. If you're getting requests other than GET (for default response_mode) or POST (for response_mode=form_post) then investigate why you're getting those requests in the first place.
> 
> This throw is a safe guard, letting you know you might be too permissive in your routing.

we've setup our `response_mode=query` and we're expecting a `GET` request but we're still getting the  `invalid IncomingMessage method` error.

**Comment by panva** [comment]
@ktikku expecting and getting are two different things, those code says you're getting your code triggered on something else than `GET`.
