### ISSUE TITLE
Did not find expected authorization request details in session.

### ISSUE THREAD

**Issue by abhinavtcs** [panva/node-openid-client#237]
**Describe the bug**
Did not find expected authorization request details in session.

```
Error: did not find expected authorization request details in session, req.session["oidc:federate.xh1.lilly.com"] is undefined
    at C:\Users\workspace\Auth Module\scout_auth_module\node_modules\openid-client\lib\passport_strategy.js:126:13
    at OpenIDConnectStrategy.authenticate (C:\Users\C286160\workspace\Auth Module\scout_auth_module\node_modules\openid-client\lib\passport_strategy.js:174:5)
    at attempt (C:\Users\workspace\Auth Module\scout_auth_module\node_modules\Passport\lib\middleware\authenticate.js:366:16)
    at authenticate (C:\Users\workspace\Auth Module\scout_auth_module\node_modules\Passport\lib\middleware\authenticate.js:367:7)
    at router.use (C:\Users\workspace\Auth Module\scout_auth_module\index.js:98:8)
    at Layer.handle [as handle_request] (C:\Users\workspace\Auth Module\testApp\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\workspace\Auth Module\testApp\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\workspace\Auth Module\testApp\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\workspace\Auth Module\testApp\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\workspace\Auth Module\testApp\node_modules\express\lib\router\index.js:275:10)
```

**To Reproduce**
```
exports.authenticate = async (router) => {
    router.set('trust proxy', true);
    router.use(session({
        saveUninitialized:'true',
        resave:'true',
        secret: "hello",
        name: 'id',
        cookie: {
          httpOnly: 'false',
          maxAge: 1800000,
          path: '/',
          sameSite: undefined,
          secure: undefined,
        },
        proxy: undefined,
        rolling:'true',
        unset: 'keep',
      }))

    router.use(bodyParser.json());
    router.use(bodyParser.urlencoded({ extended: true }));

    router.use(passport.initialize());
    router.use(passport.session());

    router.use('/login',
    (req, res, next) => {
      const redirectUri = `http://localhost:3000/auth/callback`;
      const state = req.originalUrl;

      return passport.authenticate('oidc',{ redirect_uri: redirectUri, state },)(req, res, next);
    },
    (req, res) => {
        req.session.test="Hello session";
      res.redirect(req.originalUrl || '/');
    });

router.use('/auth/callback',(req,res, next)=>{
    console.log("In callback router", req.query)
    console.log("Session Value",req.session)

    const redirectUri = `http://localhost:3000/auth/callback`;
    if (req.query.code) {
      const successRedirect = req.session.returnTo || '/';

      return passport.authenticate(
        'oidc',
        { successRedirect, failureRedirect: '/', redirect_uri: redirectUri },
      )(req, res, next);
    }
    console.log(req.session)
    return res.redirect('/')
    // console.log(req.session)
    // res.redirect('/');
})

    const openidIssuer = await discoverIssuerWithRetries()
    .catch(() => {
        console.log("Error in issuer")
      process.exit(1);
    });

    let client = new openidIssuer.Client({
        client_id: 'bxxxxxxxxxxxxxxxxxxx',
        client_secret: "hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxi",
      });
      

    const params = {
        response_type: 'code',
        scope: 'openid auth_adaptivemfa',
      };

    passport.use(
        'oidc',
        new Strategy({ client, params },
          (tokenset, userinfo, done) => {
            console.log(`User has been authenticated: ${tokenset.claims.sub}`);
            tokenset.claims = tokenset.claims();
            tokenset.sub = tokenset.claims.sub;
            tokenset.userinfo = { ...userinfo };
            return done(null, tokenset);
          }),
      );

      return router;

}
```

Steps to reproduce the behaviour:

1.  Destroy the session.
2.  Try to Login again or First Time Login

**Expected behaviour**
It should set the token in session and redirected to Home ("/") 

**Environment:**
 - openid-client version:  v3.7.3
 - node version: v.10.15.3

**Additional context**
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
I believe the error says it all, on the initial request that results in redirecting to the issuer's `authorization_endpoint` the strategy set an object to the session's `oidc:federate.xh1.lilly.com` property.

Said object is not there when getting the callback. You should investigate why that's the case.

**Comment by patmooney** [comment]
Had similar issue:
Either:
 - Two simultaneous calls by the same browser, a race condition means the first request deletes the cookies before the second finishes
 - Passport doesn't save the server-side session in time before user is returned from auth endpoint. This is due to passport not waiting for session.save() to complete before the redirect.

**Comment by Asafkbalink** [comment]
> Had similar issue:
> Either:
> 
> * Two simultaneous calls by the same browser, a race condition means the first request deletes the cookies before the second finishes
> * Passport doesn't save the server-side session in time before user is returned from auth endpoint. This is due to passport not waiting for session.save() to complete before the redirect.

What is the solution then?
I'm having the same problem when trying to initiate the authentication from a native ios app.
The ios app reaching `/auth/login` to initiate login, the redirect uri in the strategy is set to `auth/callback` but after logging in it fails with this error message.

@abhinavtcs maybe you managed to solve it?
