### ISSUE TITLE
RequestError: connect ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by franleplant** [panva/node-openid-client#320]
#### Describe the bug

 - Node.js version: 14
 - OS & version: docker/alpine

Using this library through https://github.com/panva/node-openid-client , when making the initial request of the open id connect discovery document it throws this weird error

#### Actual behavior

```
2020-12-28T21:49:39.282Z tenx:lib-auth:http >>> Request GET https://private-oidc-provider.com//.well-known/oauth-authorization-server
2020-12-28T21:49:39.282Z tenx:lib-auth:http Headers: {
  'user-agent': 'openid-client', // the one that we use works
  accept: 'application/json',
  'accept-encoding': 'gzip, deflate, br'
}
2020-12-28T21:49:39.282Z tenx:lib-auth:http Body undefined
2020-12-28T21:49:39.283Z tenx:lib-auth:http >>> Request GET https://private-oidc-provider.com/.well-known/openid-configuration
2020-12-28T21:49:39.283Z tenx:lib-auth:http Headers: {
   'user-agent': 'openid-client',// the one that we use works
  accept: 'application/json',
  'accept-encoding': 'gzip, deflate, br'
}
2020-12-28T21:49:39.283Z tenx:lib-auth:http Body undefined
2020-12-28T21:49:39.297Z tenx:lib-auth:init Error creating costar client AggregateError:
    RequestError: connect ECONNREFUSED 127.0.0.1:443
        at ClientRequest.<anonymous> (/usr/src/app/node_modules/got/dist/source/core/index.js:957:25)
        at /usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:68:19
        at Scope._activate (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:44:14)
        at Scope.activate (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:13:17)
        at ClientRequest.<anonymous> (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:67:20)
        at ClientRequest.req.emit (/usr/src/app/node_modules/dd-trace/packages/datadog-plugin-http/src/client.js:93:21)
        at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    RequestError: connect ECONNREFUSED 127.0.0.1:443
        at ClientRequest.<anonymous> (/usr/src/app/node_modules/got/dist/source/core/index.js:957:25)
        at /usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:68:19
        at Scope._activate (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:44:14)
        at Scope.activate (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:13:17)
        at ClientRequest.<anonymous> (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:67:20)
        at ClientRequest.req.emit (/usr/src/app/node_modules/dd-trace/packages/datadog-plugin-http/src/client.js:93:21)
        at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at maybeSettle (/usr/src/app/node_modules/p-some/index.js:31:11)
    at /usr/src/app/node_modules/p-some/index.js:69:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

#### Expected behavior

This request to work.

This request works 

- running the code locally on a lot of developer machines
- works via curl/wget from inside the Kube cluster node and pods

But it doesn't work via node-oidc-client and got when running side the pod / container.

#### Code to reproduce

working on it, but it is hard because it only fails inside the container inside the pod inside the kube cluster

#### Checklist

- [ x ] I have read the documentation.
- [ x ] I have tried my code with the latest version of Node.js and Got.

Also reported in got's repo https://github.com/sindresorhus/got/issues/1515

**Comment by franleplant** [comment]
Any clues to solve this will be highly appreciated

**Comment by panva** [comment]
> Any clues to solve this will be highly appreciated

There is no bug here, you're simply asking for help diagnose your environment / build issues. Please open a Q&A discussion instead.

**Comment by agix** [comment]
I have exactly the same issue. Still debugging.

**Comment by franleplant** [comment]
Check the linked “got” issue, there are further clues there. Tldr: there
are libraries potentially unrelated to openid-client and got that mess up
with the global native Nodejs http(s) clients causing this problems,
updating or removing those problematic libs will fix the problem. It’s
kinda nobody’s fault but a problem in the ecosystem

**Comment by agix** [comment]
awesome... will be fun to debug :). Thanks for the tips.

**Comment by franleplant** [comment]
Oh it’s a blast jajajaja

**Comment by agix** [comment]
Ok I found it's related to https://github.com/DataDog/dd-trace-js usage in our case

**Comment by dnikomon** [comment]
I am getting this same error running locally. Every other method seems working but `Issuer.discover ` does not.

**Comment by agix** [comment]
So you have to check all your other libraries, remove it one by one to find out the one who messed up with got.

**Comment by panva** [comment]
@dnikomon happy hunting!

**Comment by panva** [comment]
If you don't mind that there's a dependency in your dependency tree that is messing with node's core https request capabilities, go ahead!

**Comment by agix** [comment]
> fetching .well-known endpoints manually

if you use got to fetch it manually (maybe other http library too) it will do the same.

**Comment by franleplant** [comment]
also when you do any other thing with the library such as fetching user
info, refreshing the token et al should get into this error so there's no
easy way around it.

Perhaps this lib could be request-library-agnostic and so if people really
want to can replace got for superagent (to say an example).

You can always fork it and do that yourself.

**Comment by agix** [comment]
Better to track down the one messing with native https requests

**Comment by panva** [comment]
@franleplant the problem is not with got. It's that e.g. agent-base that one of your dependencies uses patches node https.request. Got just happens to always parse a string url to an URL object that surfaces this problem with agent-base.

**Comment by panva** [comment]
Libraries identified to this so far (note they may be intrinsic dependencies of yours)

https://github.com/DataDog/dd-trace-js
https://github.com/mailjet/mailjet-apiv3-nodejs
https://github.com/TooTallNate/node-agent-base

**Comment by franleplant** [comment]
But not all libraries use the same underlying http clients, nevertheless I
agree with you thats better to track down the dep thats causing the problem

**Comment by panva** [comment]
@franleplant i can guarantee that all libs use the underlying node core https module which this unfortunately designed library is patching.

**Comment by dnikomon** [comment]
> Libraries identified to trigger this so far (note they may be intrinsic dependencies of yours and i did not look to confirm they are the last dependency in the chain)
> 
> https://github.com/DataDog/dd-trace-js
> https://github.com/mailjet/mailjet-apiv3-nodejs
> https://github.com/TooTallNate/node-agent-base
> mailgun-js

Thank you. We have mailgun-js in dependencies. And it seems it was the only package causing problems in our case.

`"mailgun-js": "^0.22.0",`
