### ISSUE TITLE
Undefined value returned from authorizationCallback breaking passport

### ISSUE THREAD

**Issue by morungos** [panva/node-openid-client#50]
Following on from #49, I still can't get passport up and running. The current issue is that `authorizationCallback` returns an undefined value. 

The query parameters for the callback endpoint are shown as:

state:XXX
code:XXX
authuser:0
session_state:61c305bab9bcb8d691b7996fdbe40120becb5656..2bd3
prompt:none

My read of the code is that because `id_token` is not set, this method won't ever return a defined value. 

I really didn't want to have to read the standard, but it does seem that callbacks that only set `code` are possible, as seems to be happening. 

However, the code backtrace is coming from a regular `router.use(passport.authenticate('oidc'));` that I attach to my endpoints, and I have no idea how these values make their way into a regular protected passport endpoint. I'm assuming I have to do something like `passport.authenticate('oidc')` as a middleware on my endpoints, but I am guessing here to some extent.

Is this how I am supposed to protect an endpoint when using with passport?

Any suggestions on how to move this forward?

```
TypeError: Cannot read property 'then' of undefined
    at OpenIDConnectStrategy.authenticate (/mnt/data/git/turalt-demo/node_modules/openid-client/lib/passport_strategy.js:94:7)
    at attempt (/mnt/data/git/turalt-demo/node_modules/passport/lib/middleware/authenticate.js:361:16)
    at authenticate (/mnt/data/git/turalt-demo/node_modules/passport/lib/middleware/authenticate.js:362:7)
    at Layer.handle [as handle_request] (/mnt/data/git/turalt-demo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/mnt/data/git/turalt-demo/node_modules/express/lib/router/index.js:317:13)
    at /mnt/data/git/turalt-demo/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/mnt/data/git/turalt-demo/node_modules/express/lib/router/index.js:335:12)
    at next (/mnt/data/git/turalt-demo/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/mnt/data/git/turalt-demo/node_modules/express/lib/router/index.js:174:3)
    at router (/mnt/data/git/turalt-demo/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/mnt/data/git/turalt-demo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/mnt/data/git/turalt-demo/node_modules/express/lib/router/index.js:317:13)
    at /mnt/data/git/turalt-demo/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/mnt/data/git/turalt-demo/node_modules/express/lib/router/index.js:335:12)
    at next (/mnt/data/git/turalt-demo/node_modules/express/lib/router/index.js:275:10)
    at SessionStrategy.strategy.pass (/mnt/data/git/turalt-demo/node_modules/passport/lib/middleware/authenticate.js:338:9)
```

**Comment by panva** [comment]
Of course passing the authenticate call into every single resource middleware chain is going to fail on you - the strategy is for starting and consuming an authorization request and response callback. Nothing more.

**Comment by morungos** [comment]
Aha! So, in order to use with passport, I need to protect the endpoints entirely separately, with something like:

```
function checkAuthentication (options) {
  return function (req, res, next) {
    if (req.isAuthenticated()) {
      return next()
    }
    res.redirect((options || {}).loginRedirect || '/');
  }
}
router.use(checkAuthentication());
```

That does seem to move it forward. Passport's documentation isn't exactly wonderful, and without an example that does seem to be a gap here. I'll maybe see if I can work out an example I can make in a PR if you're interested.

**Comment by panva** [comment]
Any and all improvements, additions, typo fixes and such contributions are indeed very welcome. Happy to hear you're progressing.
