### ISSUE TITLE
AssertionError: expected 200 OK with body, got 200 OK without one

### ISSUE THREAD

**Issue by andystevensname** [panva/node-openid-client#53]
I'm receiving this error with my token response. Is this a failure on Twitch's part to respond with the status code _inside_ the body? Any ideas on how I should proceed?

```
Response { 
  statusCode: 200,
  headers:
   {
     'content-type': 'application/json; charset=utf-8',
     server: 'nginx',
     'access-control-allow-origin': '*',
     'cache-control': 'no-cache, no-store, must-revalidate, private',
     expires: '0',
     pragma: 'no-cache',
     'twitch-trace-id': '...',
     'x-ctxlog-logid': '...',
     'front-end-https': 'on',
     'timing-allow-origin': 'https://www.twitch.tv',
     vary: 'Accept-Encoding',
     date: 'Thu, 14 Sep 2017 19:14:58 GMT',
     'content-length': '209',
     connection: 'close' },
  trailers: {},
  httpVersion: '1.1',
  url: 'https://api.twitch.tv/api/oauth2/token',
  method: null,
  body: '{
    "refresh_token":"...",
    "access_token":"...",
    "scope":"channel_check_subscription chat_login user_follows_edit user_read",
    "expires_in":0
  }'
}
```
```
{ AssertionError: expected 200 OK with body, got 200 OK without one
    at expectResponseBody (/Users/ovenbird/Documents/Projects/AStreamForVoices/astreamforvoices/node_modules/openid-client/lib/expect_response.js:8:5)

    at process._tickCallback (internal/process/next_tick.js:103:7)
  name: 'AssertionError',
  actual: '',
  expected: true,
  operator: '==',
  message: 'expected 200 OK with body, got 200 OK without one',
  generatedMessage: false }
```

**Comment by panva** [comment]
> respond with the status code inside the body

that's not it. i can see the JSON body :-( weird

**Comment by panva** [comment]
1) discovered Issuer using `Issuer.discover('https://passport.twitch.tv');
2) set up a new client using `new issuer.Client({ client_id, client_secret, redirect_uris: [...], token_endpoint_auth_method: 'client_secret_post' });`
3) I am getting a valid token set and validating it too.

```
TokenSet {
  id_token: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjEifQ.eyJzdWIiOiIxMjUyMzQ4NTIiLCJpc3MiOiJodHRwczovL2FwaS50d2l0Y2gudHYvYXBpIiwiYXVkIjoidnA1dnJpMTdjOWY5YTc0eGlteXNhcHgyem43amVxIiwiZXhwIjoxNTA1NDIwNTY4LCJpYXQiOjE1MDU0MTk2Njh9.WP5EDO4u9DeW3Xi7cSJZrY9UxhXdZb9pjB0FENlHyHqWbzyuFQBKSOwXGdWC-6Tk5TJ2jX_ad--H5wRLcQSYO-aKUPIkQvDEre4dFNSvK_VR-HOU2HgNjJMHLYcdKjnue0hOtDn5e-fu9TwLlaQdryBEZ3YMsBW4kkaSfSFA3IDqCiYeLl6yF7ZnuCFmXxj19iU6dRdA2Hlg8AynymGm60XTrSlDW8w3IoQ6WuAphZZxvL8QRKsr_WoNRryOu2CfW8V0851R-mHCnhjqFd-VoBDUhJrsplbeqVA0MQwKaC26zcsbyvdxfRg3doCv2cZs85WRv880tl2vire_tZ1fuQ',
  refresh_token: '...',
  access_token: '...',
  scope: 'openid',
  expires_at: 1505434085 }
```

**Comment by panva** [comment]
can you paste your server code?

**Comment by andystevensname** [comment]
Thanks for getting back to me, I set my client up manually:

```
const twitchIssuer = new Issuer({
  issuer: 'https://api.twitch.tv',
  authorization_endpoint: 'https://api.twitch.tv/kraken/oauth2/authorize',
  token_endpoint: 'https://api.twitch.tv/api/oauth2/token',
  userinfo_endpoint: 'https://api.twitch.tv/kraken/user',
  jwks_uri: 'https://api.twitch.tv/api/oidc/keys'
});

const twitchClient = new twitchIssuer.Client({
  client_id: ... ,
  client_secret: ... ,
  token_endpoint_auth_method: 'client_secret_post'
});

const twitchParams = {
  redirect_uri: protocol + '//' + callbackHost + callbackPort + '/auth/twitch/callback',
  scope: 'user_read user_follows_edit channel_check_subscription chat_login'
};

const passReqToCallback = true;

passport.use('twitchOIDC', new OIDCStrategy({ client: twitchClient, params: twitchParams, passReqToCallback: passReqToCallback }, (req, tokenset, userinfo, done) => {
  console.log('tokenset', tokenset);
  console.log('access_token', tokenset.access_token);
  console.log('id_token', tokenset.id_token);
  console.log('claims', tokenset.claims);
  console.log('userinfo', userinfo);
 
  // I don't have this in my code, I'm just interested in seeing the console output right now before incorporating the user model.
  /*
  models.User.findOne({ id: tokenset.claims.sub }, function (err, user) {
    if (err) return done(err);
    return done(null, user);
  });*/

  return done(err);

}));
```

**Comment by panva** [comment]
this is likely your problem

```
  userinfo_endpoint: 'https://api.twitch.tv/kraken/user',
```

this is not where userinfo is. just use discovery as in my example instead of setting up the issuer on your own. https://passport.twitch.tv/.well-known/openid-configuration

**Comment by panva** [comment]
not to mention that the userinfo endpoint twitch has does not work as it should according to the specification.

1) remove userinfo from your callback arguments
2) add openid to your list of requested scopes
3) discover issuer

you will get your tokens then using this library

**Comment by andystevensname** [comment]
Thank you for your help, I managed to receive a token using the discovery method without implementing the 'userinfo' argument.
