### ISSUE TITLE
Cannot assign to read only property 'dpopProof' of object '#<Client>'

### ISSUE THREAD

**Issue by gempain** [panva/node-openid-client#618]
**Describe the bug**
I followed the quick start guide but I end up getting:

```
reason TypeError: Cannot assign to read only property 'dpopProof' of object '#<Client>'
    at _clone (.../node_modules/clone/clone.js:162:16)
    at _clone (.../node_modules/clone/clone.js:162:18)
    at _clone (.../node_modules/clone/clone.js:162:18)
    at _clone (.../node_modules/clone/clone.js:162:18)
    at .../node_modules/clone/clone.js:94:19
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**To Reproduce**
I tried to make a minimal reproductible example but I wasn't able to:

```ts
import { Issuer } from "openid-client";

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function main() {
  const googleIssuer = await Issuer.discover("https://accounts.google.com");
  const client = new googleIssuer.Client({
    client_id: "...",
    client_secret: "...",
    redirect_uris: ["..."],
    response_types: ["code"],
  });

  await sleep(10000);
}

process.on("unhandledRejection", (err) => {
  console.error(err);
  process.exit(1);
});

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
```

**Expected behaviour**
I would expect promises to be awaited for.

**Environment:**
 - openid-client version: v5.4.3
 - node version: v18.17.0

**Additional context**

 - [x] the bug is happening on latest openid-client too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by gempain** [comment]
Just found the issue. I was trying to put the client in a node-cache instance and they're using `clone()` by default.

Doing this solved the issue: 

```ts
const clientCache = new nodeCache({ stdTTL: 1440000, useClones: false });
```
