### ISSUE TITLE
state mismatch

### ISSUE THREAD

**Issue by lewisloofis** [panva/node-openid-client#67]
Hello,

When I tried to do authorization code flow, I always have an this error:
```
Error: state mismatch
    at Client.authorizationCallback (/var/www/html/node_modules/openid-client/lib/client.js:309:29)
    at OpenIDConnectStrategy.authenticate (/var/www/html/node_modules/openid-client/lib/passport_strategy.js:137:27)
    at attempt (/var/www/html/node_modules/passport/lib/middleware/authenticate.js:361:16)
    at authenticate (/var/www/html/node_modules/passport/lib/middleware/authenticate.js:362:7)
    at Layer.handle [as handle_request] (/var/www/html/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/html/node_modules/express/lib/router/index.js:317:13)
    at /var/www/html/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/html/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/html/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle [as handle_request] (/var/www/html/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/var/www/html/node_modules/express/lib/router/index.js:317:13)
    at /var/www/html/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/html/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/html/node_modules/express/lib/router/index.js:275:10)
    at SessionStrategy.strategy.pass (/var/www/html/node_modules/passport/lib/middleware/authenticate.js:338:9)
    at SessionStrategy.authenticate (/var/www/html/node_modules/passport/lib/strategies/session.js:75:10)
    at attempt (/var/www/html/node_modules/passport/lib/middleware/authenticate.js:361:16)
    at authenticate (/var/www/html/node_modules/passport/lib/middleware/authenticate.js:362:7)
    at Layer.handle [as handle_request] (/var/www/html/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/html/node_modules/express/lib/router/index.js:317:13)
    at /var/www/html/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/html/node_modules/express/lib/router/index.js:335:12)
```

And when I debug my node-oidc-provider, it seems my state is changing like this
```
user-service_1   | user-servi | [2017-12-19T15:29:32.333] [INFO] default - ==== USER SERVICE ====
user-service_1   | user-servi | [2017-12-19T15:29:32.336] [INFO] default - BEGINNING USER SERVICE
user-service_1   | user-servi | [2017-12-19T15:29:32.344] [INFO] default - REGISTERING REDIS TO DI
user-service_1   | user-servi | [2017-12-19T15:29:32.345] [INFO] default - REGISTRATION DONE.
user-service_1   | user-servi | [2017-12-19T15:29:32.489] [INFO] default - REGISTERING SERVICES TO DI
user-service_1   | user-servi | NOTICE: a draft/experimental feature (sessionManagement) enabled, future updates to this feature will be released as MINOR releases
user-service_1   | user-servi | [2017-12-19T15:29:32.517] [INFO] default - REGISTRATION DONE.
user-service_1   | user-servi | [2017-12-19T15:29:32.517] [INFO] default - STARTING SERVER...
user-service_1   | user-servi | [2017-12-19T15:29:32.669] [INFO] default - SERVER STARTED AT PORT: 3000
user-service_1   | user-servi | 2017-12-19T15:30:06.470Z oidc-provider:authentication:accepted uuid=144baad5-2a9b-4977-b21c-f0ad050ff7ad Params { acr_values: undefined, claims: undefined, claims_locales: undefined, client_id: 'zELcpfANLqY7Oqas', code_challenge: undefined, code_challenge_method: undefined, display: undefined, id_token_hint: undefined, login_hint: undefined, max_age: undefined, nonce: undefined, prompt: undefined, redirect_uri: 'https://docker.for.mac.localhost/auth/cb', registration: undefined, request: undefined, request_uri: undefined, response_mode: 'query', response_type: 'code', scope: 'openid email', state: '7f31cd25-377f-4cc1-8f41-e9578052702f', ui_locales: undefined }
user-service_1   | user-servi | 2017-12-19T15:30:06.475Z oidc-provider:authentication:interrupted uuid=144baad5-2a9b-4977-b21c-f0ad050ff7ad interaction={ error: 'login_required', error_description: 'End-User authentication is required', reason: 'no_session', reason_description: 'Please Sign-in to continue.' }
user-service_1   | user-servi | [2017-12-19T15:30:06.501] [INFO] default - see what else is available to you for interaction views Session {
user-service_1   | user-servi |   returnTo: 'https://docker.for.mac.localhost:81/oidc/auth/144baad5-2a9b-4977-b21c-f0ad050ff7ad',
user-service_1   | user-servi |   interaction: 
user-service_1   | user-servi |    { error: 'login_required',
user-service_1   | user-servi |      error_description: 'End-User authentication is required',
user-service_1   | user-servi |      reason: 'no_session',
user-service_1   | user-servi |      reason_description: 'Please Sign-in to continue.' },
user-service_1   | user-servi |   uuid: '144baad5-2a9b-4977-b21c-f0ad050ff7ad',
user-service_1   | user-servi |   params: 
user-service_1   | user-servi |    { client_id: 'zELcpfANLqY7Oqas',
user-service_1   | user-servi |      redirect_uri: 'https://docker.for.mac.localhost/auth/cb',
user-service_1   | user-servi |      response_mode: 'query',
user-service_1   | user-servi |      response_type: 'code',
user-service_1   | user-servi |      scope: 'openid email',
user-service_1   | user-servi |      state: '7f31cd25-377f-4cc1-8f41-e9578052702f' },
user-service_1   | user-servi |   id: '144baad5-2a9b-4977-b21c-f0ad050ff7ad' }
user-service_1   | user-servi | 2017-12-19T15:30:24.084Z oidc-provider:authentication:resumed uuid=144baad5-2a9b-4977-b21c-f0ad050ff7ad { login: { account: '5a37ed54852e8d0044de7336', acr: '1', remember: true, ts: 1513697424 }, consent: { scope: 'openid email' } }
user-service_1   | user-servi | NOTICE: default helper interactionCheck called, you should probably change it in order to to define the policy for requiring End-User interactions.
user-service_1   | user-servi | 2017-12-19T15:30:24.092Z oidc-provider:authentication:success uuid=144baad5-2a9b-4977-b21c-f0ad050ff7ad { code: 'OWNiMjEwOGYtNmZjMy00ZGQzLTkxNzgtODBmYTAyYTEzN2Y5_8g2B8_NsKHh5mBRdKge6xYGJfvDCS70KFI97jI1TBLJ7Sk0gWvVXOFpCFux_4I2v9DlFePu8DtCv_XplvVnkA', state: '7f31cd25-377f-4cc1-8f41-e9578052702f', session_state: '349c1feee28805f640427f0bfeabf073e3102518ecdf8bef1664977ccbd6c8e7.6f931315a4e555e7' }
```

I don't know what is the issue here, what is being compared. I am using self signed certificate for development, and also two services in my system, one is api-gateway as gateway and proxy and other one is user-service as my authorization service. I activate express session in my api-gateway with cookie secure to true in my api-gateway
 `app.use(session({
    secret: 'keyboard cat',
    resave: false,
    saveUninitialized: true,
    cookie: { secure: true },
  }));`

Any other problem with my setting that cause error?

**Comment by lewisloofis** [comment]
I will also attach the cookie here. In this picture the request and response cookie state are different. Should this two be the same?

<img width="1093" alt="screen shot 2017-12-19 at 22 41 17" src="https://user-images.githubusercontent.com/15197755/34165067-e0387a36-e50d-11e7-9e96-36c34e2899d8.png">

**Comment by panva** [comment]
You're mixing up things, state parameter, session_state and specific state cookie the OP has are three different topics.

The state coming in and out of the provider is the same, i don't see any change there (`7f31cd25-377f-4cc1-8f41-e9578052702f` from your logs). Can you check the client side session is loaded properly and that state is indeed there? Checking the `state` is the same is the first the client does. I think apart from checking that a session object is simply present the strategy could use some assertions that the state is present during callback phase. Also throwing an assertion with actual/expected instead of just Error is something i'll introduce.

**Comment by lewisloofis** [comment]
Ok, so how do I check for the state compared in the strategy?

**Comment by panva** [comment]
```
app.use(session({ secret: 'keyboard cat', resave: false, saveUninitialized: true, cookie: { secure: true }, }));
```

you're defining it, you should see a namespace in there the strategy is pushing on initiate and expecting on callback phase

**Comment by lewisloofis** [comment]
okay so here is my codes on localhost for the api-gateway and my strategy. for some reason my console.log in `/auth/cb` is not triggered so i don't really know how to debug it.

server.js
```
  const app = express();

  app.use(logger('dev'));
  app.use(cors());
  app.use(helmet());
  app.use(session({
    secret: 'keyboard cat',
    resave: false,
    saveUninitialized: true,
    cookie: { secure: true },
  }));
  app.use(passport.initialize());
  app.use(passport.session());
  app.use('/openapi.json', express.static(path.join(__dirname, '..', 'openapi.json')));
  // app.use(cookieParser());

  // Error handling
  app.use((err, req, res, next) => {
    console.error(`${new Date().toUTCString()} :: Express error ${err}`);
    reject(new Error(`Something went wrong!, err: ${err}`));
    if (res.headersSent) {
      return next(err);
    }

    let resStatus = status.BAD_GATEWAY;

    if (err.name === 'ValidationError') {
      resStatus = status.BAD_REQUEST;
    }

    return res.status(resStatus).json({
      code: resStatus,
      type: err.name,
      message: err.message,
    });
  });

  app.use('/api/users', proxy({
    target: 'https://user-service:3000',
    pathRewrite: {
      '^/api/users': '/users',
    },
    secure: false,
  }));

  app.use('/oidc', proxy({
    target: 'https://user-service:3000/oidc',
    pathRewrite: {
      '^/oidc': '/',
    },
    changeOrigin: true,
    secure: false,
  }));

  app.use('/api/oidc', proxy({
    target: 'https://user-service:3000/oidc',
    pathRewrite: {
      '^/api/oidc': '/',
    },
    protocolRewrite: 'https',
    secure: false,
  }));

  app.use('/api/stories', proxy({
    target: 'http://app-service:3000',
    pathRewrite: oldpath => oldpath.replace('/api/stories', '/stories'),
    secure: true,
  }));

  return oidcStrategy.registerStrategy(passport).then((oidcauth) => {
    app.use('/auth', oidcauth.authenticate('oidc'));
    app.use('/auth/cb', (req, res, next) => {
      console.log('::@@REQ SESSION', req.session);
      oidcauth.authenticate('oidc', (err, user, info) => {
        console.log('GET USER', user);
        console.log('INFO', info);
        if (err) return next(err);
        if (!user) return res.redirect('/login');
        return req.logIn(user, (error) => {
          if (err) return next(error);
          return res.redirect('/');
        });
      })(req, res, next);
    });

    const server = spdy.createServer(options.ssl, app).listen(options.port, () => resolve(server));

    return server;
  }).catch(err => console.error(':: ERROR ON SERVER', err));
```

oidcStrategy.js
```
'use strict';

const { Issuer } = require('openid-client');
const rp = require('request-promise');
const { Strategy } = require('openid-client');
const jose = require('node-jose');
const keystore = require('./keystore.json');
const ssl = require('../ssl');

const registerStrategy = passport => new Promise((resolve, reject) => {
  if (!passport) {
    return reject(new Error('Passport module is required for strategy registration'));
  }

  const params = {
    redirect_uri: 'https://docker.for.mac.localhost/auth/cb',
    scope: 'openid email',
  };

  const oidcProviderUrl = 'https://docker.for.mac.localhost:81';

  return jose.JWK.asKeyStore(keystore)
    .then((keyobj) => {
      const oidcIssuer = new Issuer({
        issuer: `${oidcProviderUrl}`,
        authorization_endpoint: `${oidcProviderUrl}/oidc/auth`,
        token_endpoint: `${oidcProviderUrl}/oidc/token`,
        userinfo_endpoint: `${oidcProviderUrl}/oidc/me`,
        jwks_uri: `${oidcProviderUrl}/oidc/certs`,
      });
      const client = new oidcIssuer.Client({
        client_id: 'testone',
        client_secret: 'testtesttest',
      }, keyobj);

      passport.use('oidc', new Strategy({ client, params }, (tokenset, userinfo, done) => {
        console.log('TOKENSET', tokenset);
        const getUserOptions = {
          uri: `https://user-service:3000/users/${tokenset.claims.sub}`,
          cert: ssl.cert,
          key: ssl.key,
          json: true,
        };
        rp(getUserOptions)
          .then((user) => {
            if (!user) return done(null, false);
            return done(null, user);
          })
          .catch((err) => {
            console.error('ERROR ON USER SERVICE VALIDATE CALL');
            done(err);
          });
      }));

      passport.serializeUser((user, done) => {
        console.log('SERIALIZING USER ID', user);
        done(null, user._id);
      });

      passport.deserializeUser((id, done) => {
        console.log('::@@DESERIALIZE USER ID', id);
        const getUserOptions = {
          uri: `https://user-service:3000/users/${id}`,
          cert: ssl.cert,
          key: ssl.key,
          json: true,
        };
        rp(getUserOptions)
          .then((user) => {
            if (!user) return done(null, false);
            return done(null, user);
          })
          .catch((err) => {
            console.error('ERROR ON USER SERVICE SERIALIZE USER');
            done(err);
          });
      });

      return resolve(passport);
    })
    .catch((err) => {
      console.error('ERROR ON JOSE KEYSTORE');
      return reject(err);
    });
});

module.exports = Object.assign({}, { registerStrategy });
```

**Comment by lewisloofis** [comment]
Ok so I'm doing same console.log for the /auth and /auth/cb route
```
return oidcStrategy.registerStrategy(passport).then((oidcauth) => {
    app.use('/auth', (req, res, next) => {
      console.log('::@@REQ SESSION', req.session);
      oidcauth.authenticate('oidc', (err, user, info) => {
        console.log('GET USER', user);
        console.log('INFO', info);
        if (err) return next(err);
        if (!user) return res.redirect('/login');
        return req.logIn(user, (error) => {
          if (err) return next(error);
          return res.redirect('/');
        });
      })(req, res, next);
    });
    app.use('/auth/cb', (req, res, next) => {
      console.log('::@@REQ SESSION', req.session);
      oidcauth.authenticate('oidc', (err, user, info) => {
        console.log('GET USER', user);
        console.log('INFO', info);
        if (err) return next(err);
        if (!user) return res.redirect('/login');
        return req.logIn(user, (error) => {
          if (err) return next(error);
          return res.redirect('/');
        });
      })(req, res, next);
    });
```

the result for the log is this
```
[HPM] Proxy rewrite rule created: "^/api/oidc" ~> "/"
api-gateway_1    | index-0    | [HPM] Proxy created: /  ->  http://app-service:3000
api-gateway_1    | index-0    | Server started successfully on port: 3000
api-gateway_1    | index-0    | ::@@REQ SESSION Session {
api-gateway_1    | index-0    |   cookie: 
api-gateway_1    | index-0    |    { path: '/',
api-gateway_1    | index-0    |      _expires: null,
api-gateway_1    | index-0    |      originalMaxAge: null,
api-gateway_1    | index-0    |      httpOnly: true,
api-gateway_1    | index-0    |      secure: true } }
api-gateway_1    | index-0    | GET /auth 302 11.235 ms - 0
api-gateway_1    | index-0    | ::@@REQ SESSION Session {
api-gateway_1    | index-0    |   cookie: 
api-gateway_1    | index-0    |    { path: '/',
api-gateway_1    | index-0    |      _expires: null,
api-gateway_1    | index-0    |      originalMaxAge: null,
api-gateway_1    | index-0    |      httpOnly: true,
api-gateway_1    | index-0    |      secure: true } }
api-gateway_1    | index-0    | GET USER undefined
api-gateway_1    | index-0    | INFO undefined
api-gateway_1    | index-0    | Error: state mismatch
api-gateway_1    | index-0    |     at Client.authorizationCallback (/var/www/html/node_modules/openid-client/lib/client.js:309:29)
api-gateway_1    | index-0    |     at OpenIDConnectStrategy.authenticate (/var/www/html/node_modules/openid-client/lib/passport_strategy.js:137:27)
api-gateway_1    | index-0    |     at attempt (/var/www/html/node_modules/passport/lib/middleware/authenticate.js:361:16)
```

I want to know when do the passport strategy set the session variable, because I'm completely following the passport strategy example but nothing mention the state param

**Comment by panva** [comment]
Hi @lewisloofis, excuse me for being blunt but i can hardly be asked to run and debug your environment. The issue is 100% connected to the way your session is set up, not being loaded, not being saved, who knows - it's not part of the client.

**Comment by lewisloofis** [comment]
so you mean in this case the only problem is in the client, nothing is really wrong on the provider right?

**Comment by panva** [comment]
Yes, there's nothing wrong with the provider, from the logs the state coming back is the same as the one coming in, the problem is in the session object the strategy relies on to save the outgoing state, it needs to be able to load it during the callback phase, it then takes the state from the request with the one it assumes it sent to authorization, but since it can't find it it compares a valid state from the provider with undefined from the session object. Instead of undefined the state that the strategy stored there during the initial phase should be there.

**Comment by panva** [comment]
Briefly looking at your sources it seems you set the cookies to be secure, that's great practice and it even seems the redirect_uri you use is https://, do you set your express/koa app to trust your ssl offloading proxy headers like `X-Real-IP`, `X-Forwarded-For`, `X-Forwarded-Proto`?

```javascript
// Koa http://koajs.com
app.proxy = true;

// Express https://expressjs.com
app.enable('trust proxy');
```

It's a wild guess but could be your culprit.

**Comment by lewisloofis** [comment]
Okay I know the problem now, it turns out I set session for both client and the oidc provider which screw things up. My route settings is also wrong, I use `app.use('/auth')` instead of `app.get('/auth')` which cause wrong call on redirection. Turns out my settings screws up 😞 😞 

Thx for creating both library btw. It's a complete set.

**Comment by panva** [comment]
@lewisloofis glad you found the culprit in your setup.
