### ISSUE TITLE
LRU is not a constructor

### ISSUE THREAD

**Issue by v0id-4lpz** [panva/node-openid-client#693]
https://github.com/panva/node-openid-client/blob/7d3471ff17d5cdf3b3ee1bfd1dec7c0a7a7321d8/lib/helpers/request.js#L8

Hi, i have this error on my Nuxt project,

I use `sidebase/nuxt-auth` with `nextauthjs/next-auth`

```sh
 ERROR  [worker reload] [worker init] LRU is not a constructor                                                                   19:08:42  

  at Object.<anonymous> (node_modules\openid-client\lib\helpers\request.js:62:16)
  at Module._compile (node:internal/modules/cjs/loader:1376:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
  at Module.load (node:internal/modules/cjs/loader:1207:32)
  at Module._load (node:internal/modules/cjs/loader:1023:12)
  at Module.require (node:internal/modules/cjs/loader:1235:19)
  at require (node:internal/modules/helpers:176:18)
  at Object.<anonymous> (node_modules\openid-client\lib\client.js:25:17)
  at Module._compile (node:internal/modules/cjs/loader:1376:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
```

Maybe use instead
```ts
const { LRUCache } = require('lru-cache')
const LRU = new LRUCache()
```

**Comment by panva** [comment]
I don't quite know what's at play in your environment / setup / deployment.

```sh
$ node -p "require('lru-cache')"     
[class LRUCache]
```
