### ISSUE TITLE
Issues on Corporate network (ECONNRESET)

### ISSUE THREAD

**Issue by codestorycooked** [panva/node-openid-client#85]
Hi @panva 
I am using the latest library and enabled `Issuer.UseRequest()`.But when application flow is completed it gives me following error:

```
Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 3128 3128:80\n    
at ClientRequest.onError (C:\\Users\\ngyr9f\\Desktop\\next-oee-app\\node_modules\\tunnel-agent\\index.js:177:17)\n    
at Object.onceWrapper (events.js:315:30)\n    
at emitOne (events.js:116:13)\n    
at ClientRequest.emit (events.js:211:7)\n    
at Socket.socketErrorListener (_http_client.js:387:9)\n    
at emitOne (events.js:116:13)\n    
at Socket.emit (events.js:211:7)\n    
at emitErrorNT (internal/streams/destroy.js:64:8)\n    
at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    
at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET'  
```
**HTTP_PROXY and HTTPS_PROXY has been set as per proxy settings**
Can you help me with this?

**Comment by panva** [comment]
Unfortunately I cannot, this is something you'll have to figure out with your corporate network administrators. `getaddrinfo ENOTFOUND` means the client was not able to connect to given address, not a library level.

**Comment by codestorycooked** [comment]
@panva  are you aware of 
```
Error: connect ETIMEDOUT 18.219.110.40:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] 
``` 
This comes on authcallback

**Comment by panva** [comment]
@codestorycooked again, not a library issue, this is http transport. If a timeout needs to be changed you can configure that.
